blogpost/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    TextAreaField,
    SubmitField)
from wtforms.validators import DataRequired


class BlogPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    text = TextAreaField('Text', validators=[DataRequired()])
    submit = SubmitField('Post')

blogpost/blog_posts/views.py
from os import abort
from flask import (
    render_template,
    url_for,
    redirect,
    request,
    Blueprint)
from flask_login import current_user, login_required
from blogpost.models import BlogPost
from blogpost.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts', __name__)


@blog_posts.route('/create', methods=['GET', 'POST'])
@login_required
def create_post():
    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post = BlogPost(title=form.title.data,
                             text=form.text.data,
                             user_id=current_user.id)
        blog_post.save_to_db()
        return redirect(url_for('core.index'))

    return render_template('create_post.html', title="Create", form=form)


@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html',
                           post=blog_post)


@blog_posts.route('/<int:blog_post_id>/update', methods=['GET', 'POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    form = BlogPostForm()

    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data
        blog_post.save_to_db()
        return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post.id))
    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text

    return render_template('create_post.html', title='Updating', form=form)


@blog_posts.route('/<int:blog_post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    blog_post.delete_from_db()

    return redirect(url_for('core.index'))

blogpost/core/views.py
# core/views.py
from flask import render_template, request, Blueprint
from blogpost.models import BlogPost

core = Blueprint('core', __name__)


@core.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.find_all(page, per_page=6)
    return render_template('index.html', blog_posts=blog_posts)


@core.route('/info')
def info():
    return render_template('info.html')

blogpost/users/views.py
# users/views.py
from flask import (
    render_template,
    url_for,
    redirect,
    flash,
    request,
    Blueprint)
from flask_login import (
    login_user,
    current_user,
    logout_user,
    login_required)
from blogpost.models import User, BlogPost
from blogpost.users.forms import (
    RegisterationForm,
    LoginForm,
    UpdateUserForm)
from blogpost.users.picture_handler import add_profile_pic

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data, password=form.password.data)
        user.save_to_db()
        flash('Thanks for registeration!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.find_by_email(form.email.data)
        if user and user.check_password(form.password.data):
            login_user(user)
            flash('Log in Success!')
            next = request.args.get('next')  # 表示之前訪問的route
            if next == None or not next[0] == '/':
                next = url_for('core.index')
            return redirect(next)
    return render_template('login.html', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit():
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.save_to_db()
        flash('User Account Updated!')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static',
                            filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html',
                           form=form,
                           profile_image=profile_image)


@users.route('/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.find_by_username_or_404(username)

    blog_posts = BlogPost.find_all_by_user(user, page, per_page=6)

    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)

blogpost/templates/_formhelpers.html
{% macro render_field(field) %}
<div class="form-floating mb-2">
    {{ field(class="form-control",placeholder=field.label.text)|safe }}
    {{ field.label }}
    {% if field.errors %}
        {% for error in field.errors %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endfor %}
    {% endif %}
</div>
{% endmacro %}

blogpost/templates/account.html
{% extends 'base.html' %}
{% from "_formhelpers.html" import render_field %}

{% block content %}
<div class="text-center">
<h1>Welcome to the page for {{ current_user.username }}</h1>
<img src="{{url_for('static',filename='profile_pics/'+current_user.profile_image)}}">
<p>{{ current_user.email }}</p>
<main class="form-signin">
<form method="POST" action="" enctype="multipart/form-data">
    {{ form.csrf_token }}
    {{ render_field(form.email) }}
    {{ render_field(form.username) }}
    {{ form.picture.label(class="form-control") }}{{ form.picture }}
    {{ form.submit(class="w-50 mt-3 btn btn-lg btn-outline-success") }}
</form>
</main>
</div>
{% endblock %}

blogpost/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{{ url_for('static',    filename='css/template.css') }}">
    {{ simplemde.css }}
    {{ simplemde.js }}
    <title>Blog Post</title>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{{url_for('core.index')}}">BlogPost</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav  me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('core.info')}}">Info</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('users.logout')}}">Log Out</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('users.account')}}">Account({{current_user.username}})</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('blog_posts.create_post')}}">Create Post</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('users.login')}}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        {% endif %}
        {% endwith %}
        {% block content %}

        {% endblock %}
    </div>
</body>

</html>

blogpost/templates/blog_post.html
{% extends 'base.html' %}

{% block content %}
<div class="h-100 p-5 bg-light border rounded-3">
    <h2 class="text-start  text-break">{{ post.title }}</h2>
    <h3 class="text-end">Written by: {{ post.author.username }}</h3>
    <h4 class="text-end">{{ post.date.strftime("%Y-%m-%d, %H:%M:%S") }}</h4>
    <p class="text-start text-break">{{ post.text|markdown }}</p>

    {% if post.author == current_user %}
        <div>
            <a href="{{url_for('blog_posts.update',blog_post_id=post.id)}}" class="btn btn-outline-primary">Update</a>
            <button type="button" class="btn btn-outline-danger"
            data-bs-toggle="modal" data-bs-target="#del_modal">Delete</button>
        </div>
    {% endif %}
<div class="modal" tabindex="-1" id="del_modal">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Delete Post?</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <p>Are you sure ?</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
            <form action="{{url_for('blog_posts.delete_post',blog_post_id=post.id)}}" method="POST">
                <input type="submit" class="btn btn-danger" value="Delete">
            </form>
        </div>
        </div>
    </div>
    </div>
</div>
{% endblock  %}

blogpost/templates/create_post.html
{% extends 'base.html' %}
{% from "_formhelpers.html" import render_field %}

{% block content %}
<main class="w-100 p-2">
<h3 class="text-center">{{ title }}</h3>
<form method="POST">
    {{ form.csrf_token }}
    {{ render_field(form.title) }}
    {{ form.text }}
    {{ simplemde.load }}
    {{ form.submit(class="w-30 mt-1 btn btn-lg btn-primary") }}
</form>
</main>
{% endblock %}

blogpost/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="h-100 p-5 bg-light border rounded-3 text-center">
    <h2>Blog Post</h2>
</div>
<div class="container">
    <div class="row g-4 py-5 row-cols-2">
        {% for post in blog_posts.items %}
            <div class="feature col">
                <h5 class="text-start text-break"><a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h5>
                <div class="text-start">
                    By <a href="{{url_for('users.user_posts',username=post.author.username)}}"> {{ post.author.username }}</a>
                    <p>Published :{{ post.date.strftime('%Y-%m-%d') }}</p>
                </div>
                <a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}" class="btn btn-outline-primary btn-sm">Read More</a>
            </div>
        {% endfor %}
    </div>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if blog_posts.has_prev %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('core.index', page=blog_posts.prev_num) }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% endif %}
    
            {%- for page in blog_posts.iter_pages(left_edge=1, left_current=2, right_current=2, right_edge=1) %}
                {% if page %}
                  {% if page != blog_posts.page %}
                    <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page) }}">{{ page }}</a></li>
                  {% else %}
                    <li class="page-item active"><a class="page-link" href="#">{{ page }}</a></li>
                  {% endif %}
                {% else %}
                  <span class=ellipsis>…</span>
                {% endif %}
            {%- endfor %}
    
            {% if blog_posts.has_next %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('core.index', page=blog_posts.next_num) }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock  %}

blogpost/templates/info.html
{% extends 'base.html' %}

{% block content %}
<div class="h-100 p-5 bg-light border rounded-3 text-center">
    <h1>Info about this app</h1>
    <p>Edit and share your post.</p>
</div>
{% endblock  %}

blogpost/templates/login.html
{% extends 'base.html' %}
{% from "_formhelpers.html" import render_field %}

{% block content %}
<main class="form-signin">
    <h3 class="text-center">Login</h3>
    <form method="POST">
        {{ form.csrf_token }}
        {{ render_field(form.email) }}
        {{ render_field(form.password) }}
        {{ form.submit(class="w-100 mt-1 btn btn-lg btn-success") }}
    </form>
</main>
{% endblock %}

blogpost/templates/register.html
{% extends 'base.html' %}
{% from "_formhelpers.html" import render_field %}

{% block content %}
<main class="form-signin">
<h3 class="text-center">Register</h3>
<form method="POST">
    {{ form.csrf_token }}
    {{ render_field(form.email) }}
    {{ render_field(form.username) }}
    {{ render_field(form.password) }}
    {{ render_field(form.pass_confirm) }}
    {{ form.submit(class="w-100 mt-1 btn btn-lg btn-primary") }}
</form>
</main>
{% endblock %}

blogpost/templates/user_blog_posts.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
<div class="text-center">
    <h1>Welcome to the page for {{ user.username }}</h1>
    <img src="{{url_for('static',filename='profile_pics/'+user.profile_image)}}">
</div>

<div class="row g-4 py-5 row-cols-2">
    {% for post in blog_posts.items %}
        <div class="feature col">
            <h5 class="text-start text-break"><a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h5>
            <div class="text-start">
                <p>Published :{{ post.date.strftime('%Y-%m-%d') }}</p>
            </div>
            <a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}" class="btn btn-outline-primary btn-sm">Read More</a>
        </div>
    {% endfor %}
</div>
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if blog_posts.has_prev %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=blog_posts.prev_num) }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% endif %}

        {%- for page in blog_posts.iter_pages(left_edge=1, left_current=2, right_current=2, right_edge=1) %}
            {% if page %}
              {% if page != blog_posts.page %}
                <li class="page-item"><a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page) }}">{{ page }}</a></li>
              {% else %}
                <li class="page-item active"><a class="page-link" href="#">{{ page }}</a></li>
              {% endif %}
            {% else %}
              <span class=ellipsis>…</span>
            {% endif %}
        {%- endfor %}

        {% if blog_posts.has_next %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=blog_posts.next_num) }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
</div>

{% endblock  %}